spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: 
    driver-class-name: org.h2.Driver
    
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        
  h2:
    console:
      enabled: true
      path: /h2-console

# JWT Configuration для тестов
jwt:
  secret: testSecretKey12345678901234567890123456789012345678901234567890
  expiration: 3600000 # 1 час для тестов

# Logging для тестов
logging:
  level:
    com.tasktracker.auth: WARN
    org.springframework.security: WARN
    org.hibernate: WARN 