spring:
  datasource:
    url: jdbc:postgresql://auth-db:5432/auth_db
    username: postgres
    password: password
    
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    
# JWT Configuration для Docker
jwt:
  secret: dockerSecretKey12345678901234567890123456789012345678901234567890
  expiration: 86400000

# Logging для Docker
logging:
  level:
    com.tasktracker.auth: INFO
    org.springframework.security: WARN
    org.hibernate: WARN 