spring:
  datasource:
    url: jdbc:postgresql://notification-db:5432/notificationdb
    username: notification_user
    password: notification_password

  redis:
    host: redis
    port: 6379

  kafka:
    bootstrap-servers: kafka:9092

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: notification-service 