# Task Service Docker Configuration
spring:
  application:
    name: task-service
  
  # Database configuration for Docker
  datasource:
    url: jdbc:postgresql://task-db:5432/task_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 300000
      connection-timeout: 30000
      validation-timeout: 5000
  
  # JPA configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: public

# Server configuration
server:
  port: 8082

# JWT Configuration
jwt:
  secret: TaskServiceSecretKey12345678901234567890123456789012345678901234567890SecretKey
  expiration: 3600000 # 1 час

# Auth Service Configuration for Docker
auth:
  service:
    url: http://gateway-service:8080/api/v1/auth
    validate-endpoint: /validate

# Logging configuration
logging:
  level:
    com.tasktracker.task: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
    org.springframework.web: WARN
    
# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always 