# Task Service Configuration
spring:
  application:
    name: task-service
  
  profiles:
    active: dev
  
  # Database configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/task_db
    username: taskuser
    password: taskpass
    driver-class-name: org.postgresql.Driver
  
  # JPA configuration
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

# Server configuration
server:
  port: 8081

# JWT Configuration
jwt:
  secret: TaskServiceSecretKey12345678901234567890123456789012345678901234567890SecretKey
  expiration: 3600000 # 1 час

# Auth Service Configuration
auth:
  service:
    url: http://localhost:8080/api/v1/auth
    validate-endpoint: /validate

# Logging configuration
logging:
  level:
    com.tasktracker.task: DEBUG
    org.springframework.security: DEBUG 